### ISSUE TITLE
Large amount of image urls are broken

### ISSUE THREAD

**Issue by weihao20** [nashory/rtic-gcn-pytorch#2]
Hello, I try to download the FasionIQ dataset but found that about 72096 image URLs are available. I hope to know whether you get a complete dataset and how many images are included in the dataset.
Can you send the datasets to google drive?
Thanks.

**Comment by yan9qu** [comment]
Same as @weihao20

**Comment by nashory** [comment]
Hi @weihao20 
Yes, I have full, complete images of FIQ (exactly 74,382 images in total), because I downloaded them right after the dataset is released.
I also found that some urls are broken, but unfortunately, I will not be able to share the full version because I am not the author of this dataset.
I recommend you to send email to original authors for FashionIQ to request the data.
Hope this will help.

**Comment by yan9qu** [comment]
> 

I have sent you an email. Please check it in min.stellastra@gmail.com. Thank you!

**Comment by weihao20** [comment]
I tried to contact the author, unfortunately, I did not get any response.

**Comment by nashory** [comment]
Dear friends,
Upon the requests, I found the [License](https://github.com/XiaoxiaoGuo/fashion-iq#license) for the Fashion-IQ dataset follows [CDLA](https://cdla.dev/), which looks to allow redistribution of data from the data recipient's side. Can anyone double-check for this?

**Comment by weihao20** [comment]
> Conditions for Sharing Data
A Data Recipient may share Data, with or without modifications, so long as the Data Recipient makes available the text of this agreement with the shared Data.

It's a great help to me!

**Comment by yan9qu** [comment]
This page may help to solve this issue. https://github.com/lugiavn/notes/blob/master/fashioniq_tirg.md

**Comment by weihao20** [comment]
@chris075966 Great job

**Comment by weihao20** [comment]
I still want to know the file size of your dataset, because I found the dataset downloaded through above link is only 1.1GB. @nashory

**Comment by weihao20** [comment]
I still want to know the file size of your dataset, because I found the dataset downloaded through above link is only 1.1GB. @nashory

**Comment by nashory** [comment]
@weihao20 Mine is 1.1G too :) good luck!
